# Generated by Django 3.0.3 on 2020-02-17 23:09

import collectionfield.models.fields
from django.db import migrations, models
import hello.models.device
import hello.models.oauth


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('token', models.CharField(default=hello.models.oauth.generate_hex_token, max_length=32, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField(default=hello.models.oauth.generate_expiration_date)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(default=hello.models.oauth.generate_hex_token, max_length=32, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField(default=hello.models.oauth.generate_expiration_date)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('action.devices.types.LIGHT', 'Light')], max_length=64)),
                ('traits', collectionfield.models.fields.CollectionField(choices=[('action.devices.traits.OnOff', 'On Off')], collection_type=set, item_type=hello.models.device.Device.Trait)),
                ('will_report_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('token', models.CharField(default=hello.models.oauth.generate_hex_token, max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecretData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=32)),
            ],
        ),
    ]
