# Generated by Django 3.0.3 on 2020-02-09 18:21

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('token', models.CharField(default=hello.models.generate_hex_token, max_length=32, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField(default=hello.models.generate_expiration_date)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(default=hello.models.generate_hex_token, max_length=32, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField(default=hello.models.generate_expiration_date)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('token', models.CharField(default=hello.models.generate_hex_token, max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
