# Generated by Django 3.0.3 on 2020-02-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_secretdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
