# Generated by Django 3.0.3 on 2020-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTraitEntry',
            fields=[
                ('trait', models.CharField(choices=[('action.devices.traits.OnOff', 'On Off')], max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('action.devices.types.LIGHT', 'Light')], max_length=64)),
                ('traits', models.ManyToManyField(to='hello.DeviceTraitEntry')),
            ],
        ),
    ]
