# Generated by Django 3.0.3 on 2020-02-16 23:18

import collectionfield.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_device_devicetraitentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_names', collectionfield.models.fields.CollectionField(collection_type=set, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('nick_names', collectionfield.models.fields.CollectionField(collection_type=set, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='will_report_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.DeviceName'),
        ),
    ]
