# Generated by Django 3.0.3 on 2020-02-17 22:44

import collectionfield.models.fields
from django.db import migrations
import hello.models.device


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200217_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceTraitEntry',
        ),
        migrations.AlterField(
            model_name='device',
            name='traits',
            field=collectionfield.models.fields.CollectionField(choices=[('action.devices.traits.OnOff', 'On Off')], collection_type=set, item_type=hello.models.device.DeviceTrait),
        ),
    ]
